#!/bin/bash
#PBS -P m68
#PBS -q normal
#PBS -l mem=96gb,walltime=24:00:00,ncpus=256
#PBS -N nudg_long

#module load intel-fc
#module load netcdf
#module load openmpi

cd /short/m68/oxr581/hre10_nudg/

#make clean && make -f makefile -j 6

mpiexec oceanM ROMS/External/ocean_waom10.in > ocean.log
#for interactive mode from command line run
#qsub -Pgh8 -qexpress -lwalltime=02:00:00,ncpus=1,mem=16gb -I
